export enum COMMANDS {
  JSON_DEL = "JSON.DEL",
  JSON_GET = "JSON.GET",
  JSON_MGET = "JSON.MGET",
  JSON_SET = "JSON.SET",
  JSON_TYPE = "JSON.TYPE",

  JSON_ARR_APPEND = "JSON.ARRAPPEND",
  JSON_ARR_INDEX = "JSON.ARRINDEX",
  JSON_ARR_INSERT = "JSON.ARRINSERT",
  JSON_ARR_LEN = "JSON.ARRLEN",
  JSON_ARR_POP = "JSON.ARRPOP",

  JSON_OBJ_KEYS = "JSON.OBJKEYS",
  JSON_DEBUG = "JSON.DEBUG",
  JSON_RESP = "JSON.RESP"
}